/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  Auth: {
    region: process.env.AWS_ORIGIN,
    userPoolId: process.env.USER_POOL_ID,
    userPoolWebClientId: process.env.CLIENT_ID,
  },
}

export default awsmobile
